name: movie_app
description: Sample Movie Application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  get: ^3.12.1
  retrofit: 1.3.4+1
  json_serializable: ^3.5.0
  transparent_image: ^1.0.0
  pedantic: ^1.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  get_test: ^3.13.3
  test: ^1.14.4
  mockito: 3.0.0
  retrofit_generator: ^1.4.0
  build_runner: ^1.10.3

flutter:
  uses-material-design: true
